ALTER TABLE phone_models
  ADD COLUMN IF NOT EXISTS camera_offset_x SMALLINT NOT NULL DEFAULT 0 AFTER logo,
  ADD COLUMN IF NOT EXISTS camera_offset_y SMALLINT NOT NULL DEFAULT 0 AFTER camera_offset_x,
  ADD COLUMN IF NOT EXISTS camera_scale DECIMAL(4,2) NOT NULL DEFAULT 1.00 AFTER camera_offset_y;
